apiVersion: v1
kind: Service
metadata:
  name: task-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  selector:
    matchLabels:
      app: task
  replicas: 1
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: 911923774628.dkr.ecr.us-east-2.amazonaws.com/demo-ecr-kyyv:tasky
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://secretUser:secretPass@ip-10-0-4-42.us-east-2.compute.internal:27017/?authSource=admin"
        - name: SECRET_KEY
          value: "345dfg435SDGF5436t435dft"
